name: upower
version: 0.7.0

description:
  Provides a client to connect to UPower - the service that does power management on Linux.

homepage: https://github.com/canonical/upower.dart

environment:
  sdk: '>=3.1.0 <4.0.0'

platforms:
  linux:

dependencies:
  dbus: ^0.7.8

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.8
  test_cov: ^1.0.1
